### ISSUE TITLE
项目运行不了

### ISSUE THREAD

**Issue by wenjiahui** [AlbieLiang/IPCInvoker#1]
你好， 我下载工程到本地， 用Android Studio打开会报错
`Error:Could not find cc.suitalk.tools:ipc-invoker-ag-extension:1.1.7.
Searched in the following locations:
    file:/home/xxx/Develop/android-studio/gradle/m2repository/cc/suitalk/tools/ipc-invoker-ag-extension/1.1.7/ipc-invoker-ag-extension-1.1.7.pom
    file:/home/xxx/Develop/android-studio/gradle/m2repository/cc/suitalk/tools/ipc-invoker-ag-extension/1.1.7/ipc-invoker-ag-extension-1.1.7.jar
    https://jcenter.bintray.com/cc/suitalk/tools/ipc-invoker-ag-extension/1.1.7/ipc-invoker-ag-extension-1.1.7.pom
    https://jcenter.bintray.com/cc/suitalk/tools/ipc-invoker-ag-extension/1.1.7/ipc-invoker-ag-extension-1.1.7.jar
    file:/home/xxx/workspace/IPCInvoker/repositories/release/cc/suitalk/tools/ipc-invoker-ag-extension/1.1.7/ipc-invoker-ag-extension-1.1.7.pom
    file:/home/xxx/workspace/IPCInvoker/repositories/release/cc/suitalk/tools/ipc-invoker-ag-extension/1.1.7/ipc-invoker-ag-extension-1.1.7.jar
Required by:
    :IPCInvoker:unspecified`

**Comment by AlbieLiang** [comment]
哇，不好意思啊，这个是新增的一个自动生成Task的功能，忘了把这个package发布到jcenter上了，现在我已经提交request了，不过需要等待accept。我push了maven配置，直接配到我的bintray账号上了，你可以pull一下最新代码看看是否能跑起来哈~

**Comment by wenjiahui** [comment]
你好， 终于可以运行起来了。 谢谢

**Comment by AlbieLiang** [comment]
好的，发现什么问题或有什么建议，欢迎反馈和pr～
