### ISSUE TITLE
多次invokeAsync问题

### ISSUE THREAD

**Issue by Qingtian239113** [AlbieLiang/IPCInvoker#3]
通过一个点击方法执行invokeAsync方法之后，如果RemoteInvoker方法里面是耗时操作，这个时候会启动多个耗时操作：
```java
while (checkTimer()) {
            try {
                Thread.sleep(1000);
                callback.onCallback(new IPCString(String.valueOf(System.currentTimeMillis())));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        Log.d("Log_for_App", "不满足条件，计时结束");`

**Comment by Qingtian239113** [comment]
主要就是想知道有没有办法去update之前执行的RemoteInvoker

**Comment by AlbieLiang** [comment]
是这样的哈，IPCInvoker AsyncTask是运行在独立的线程池里面的，目前默认配置3条线程（后续会考虑暴露接口由接入者设置），其实系统跨进程调用的Binder线程也是有上线的，也就是说，站在系统架构设计上，这部分线程资源是非常紧缺的，所以一般是不建议在Binder线程和IPCInvoker的AsyncTask线程中执行太耗时操作。

从另外一个角度上看，AsyncTask是异步接口，也就是说调用者是要有预期这里的逻辑不是被立马执行的。

**Comment by AlbieLiang** [comment]
主要就是想知道有没有办法去update之前执行的RemoteInvoker
--------------

这里的意思是要保存上一次调用的一些状态吗？

这里Task可以设置成单例的，直接加一个Annotation（@cc.suitalk.ipcinvoker.annotation.Singleton）就可以了，详细参考：https://github.com/AlbieLiang/IPCInvoker/blob/master/ipc-invoker-sample/src/main/java/cc/suitalk/ipcinvoker/sample/app/XIPCDispatcherTestActivity.java

> @Singleton
>     private static class IPCInvokeTask_PublishEvent implements IPCRemoteAsyncInvoke<Bundle, Bundle> {
> 
>         @Override
>         public void invoke(Bundle data, IPCRemoteInvokeCallback<Bundle> callback) {
>         }
>     }

**Comment by AlbieLiang** [comment]
加了个wiki文档：https://github.com/AlbieLiang/IPCInvoker/wiki/%E5%A4%9A%E6%AC%A1%E8%B0%83%E7%94%A8%E5%90%8C%E4%B8%AATask%EF%BC%8C%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E7%8A%B6%E6%80%81%E6%95%B0%E6%8D%AE%EF%BC%9F

**Comment by Qingtian239113** [comment]
感谢，这样就能更新一下task里面的参数了

**Comment by AlbieLiang** [comment]
好的，那我就关了这个issue了~
